system_configuration:
    target:
        - legacy
    requires:
        
    commands:
        - legacy: # All targets above
            - =subtask/mirrors.yaml
            - =subtask/input_method.yaml
            - =subtask/special.yaml